### ISSUE TITLE
Those "never accepted" pull requests?

### ISSUE THREAD

**Issue by tep** [mdirkse/i3ipc#4]
Hi,

I also maintain [a fork](https://github.com/tep/i3ipc) of the original proxypoke repo with a handful of my own updates plus a number of the original's never-accepted pull-requests that I merged in manually -- especially the [tree_utils update from Anon1234](https://github.com/proxypoke/i3ipc/pull/7).

I'd love to be able to drop my fork altogether and move to a more committed version but I have some dependencies on a few of those never-accepted PRs.

Is there a plan to merge those into this repo?

**Comment by mdirkse** [comment]
Yes, definitely! Sorry, I was under the impression that I had merged all of the pending PR's in the original repo. Guess not. I'll do that tomorrow.

**Comment by mdirkse** [comment]
See https://github.com/mdirkse/i3ipc-go/pull/5
